// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0Dez40K0aDM0sAXzbCoB5qGJyw817Ms',
    appId: '1:78337863592:web:f0fa56bd6b52a30477379d',
    messagingSenderId: '78337863592',
    projectId: 'foodhub-local-32bcf',
    authDomain: 'foodhub-local-32bcf.firebaseapp.com',
    storageBucket: 'foodhub-local-32bcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwdV4SiQCGNDwiQwAROjfVA221tGecO0',
    appId: '1:880724721100:android:7c7cb808e893de8b6f7169',
    messagingSenderId: '880724721100',
    projectId: 'resersala',
    storageBucket: 'resersala.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5uEpCqsMCHUmGT_rFuChRZblWMeb9tTA',
    appId: '1:880724721100:ios:4ed6c97e030ae4216f7169',
    messagingSenderId: '880724721100',
    projectId: 'resersala',
    storageBucket: 'resersala.firebasestorage.app',
    iosBundleId: 'com.example.foodhubLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZzHHW4t0k4vm_1lPzB1MdGLVlXof_edY',
    appId: '1:78337863592:ios:23f52735463d1b2c77379d',
    messagingSenderId: '78337863592',
    projectId: 'foodhub-local-32bcf',
    storageBucket: 'foodhub-local-32bcf.firebasestorage.app',
    iosBundleId: 'com.example.foodhubLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoAHm_b4vLTdIikn7ttqa-WylmKXBGWPg',
    appId: '1:880724721100:web:5e6820b3fe4923396f7169',
    messagingSenderId: '880724721100',
    projectId: 'resersala',
    authDomain: 'resersala.firebaseapp.com',
    storageBucket: 'resersala.firebasestorage.app',
    measurementId: 'G-4P0Z10FVHN',
  );

}